### ISSUE TITLE
안녕하세요 질문 드려도 될까요?

### ISSUE THREAD

**Issue by eunsu29** [park-onezero/streamlink-plugin-chzzk#1]
ModuleNotFoundError: No module named 'lzstring'

에러가 발생하는데 

pip install lzstring 으로도 해결이 안되는데

혹시 해결방법 아실까요?

**Comment by hoyori** [comment]
전 pip install rsa 이것도 해야하던데 확인해 보시죠

**Comment by eunsu29** [comment]
rsa는 이미 설치 되어있다고 뜨네요 ㅠㅠ 감사합니다

**Comment by eunsu29** [comment]
어제까지 안되다가 오늘은 갑자기 또 잘되네요... 허허
